create table if not exists public.rsvp (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(trim(name)) between 2 and 120),
    additional text not null default '' check (char_length(additional) <= 1000),
    answer text not null check (answer in ('Әрине, келемін', 'Жұбайыммен келемін', 'Келе алмаймын')),
    created_at timestamptz not null default now()
);

alter table public.rsvp enable row level security;

revoke all on table public.rsvp from anon, authenticated;
grant insert on table public.rsvp to anon, authenticated;

drop policy if exists "Guests can submit RSVP" on public.rsvp;
create policy "Guests can submit RSVP"
on public.rsvp
for insert
to anon, authenticated
with check (
    char_length(trim(name)) between 2 and 120
    and char_length(additional) <= 1000
    and answer in ('Әрине, келемін', 'Жұбайыммен келемін', 'Келе алмаймын')
);

-- There are intentionally no SELECT, UPDATE, or DELETE policies for guests.
